blank_issues_enabled: false
contact_links:
  - name: ğŸ“š DocumentaÃ§Ã£o
    url: https://github.com/seu-usuario/aplicacao-controle-de-estoque-cevesp#readme
    about: Consulte a documentaÃ§Ã£o do projeto

